package com.ggemo.tweet.pojo.dos;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was generated by Ali-Generator
 * @author 清纯的小黄瓜
 */
public class TweetInfoParam {
    /**
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     *
     * @mbg.generated
     */
    @Deprecated
    protected boolean distinct;

    /**
     *
     * @mbg.generated
     */
    protected boolean page;

    /**
     *
     * @mbg.generated
     */
    protected int pageIndex;

    /**
     *
     * @mbg.generated
     */
    protected int pageSize;

    /**
     *
     * @mbg.generated
     */
    protected int pageStart;

    /**
     *
     * @mbg.generated
     */
    protected String distinctSql;

    /**
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     * @mbg.generated
     */
    public TweetInfoParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderCondition
     * @param sortType
     * @return
     *
     * @mbg.generated
     */
    public TweetInfoParam appendOrderByClause(OrderCondition orderCondition, SortType sortType) {
        if (null != orderByClause) {
            orderByClause = orderByClause + ", " + orderCondition.getColumnName() + " " + sortType.getValue();
        } else {
            orderByClause = orderCondition.getColumnName() + " " + sortType.getValue();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     *
     * @mbg.generated
     */
    @Deprecated
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    @Deprecated
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * @param page
     * @return
     *
     * @mbg.generated
     */
    public TweetInfoParam setPage(boolean page) {
        this.page = page;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public boolean isPage() {
        return page;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * @param pageSize
     * @return
     *
     * @mbg.generated
     */
    public TweetInfoParam setPageSize(int pageSize) {
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * @param pageStart
     * @return
     *
     * @mbg.generated
     */
    public TweetInfoParam setPageStart(int pageStart) {
        this.pageStart = pageStart < 1 ? 1 : pageStart;
        this.pageIndex = (this.pageStart - 1) * this.pageSize;
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public int getPageStart() {
        return pageStart;
    }

    /**
     * @param pageStart
     * @param pageSize
     *
     * @mbg.generated
     */
    public void setPagination(int pageStart, int pageSize) {
        this.page = true;
        this.pageSize = pageSize < 1 ? 10 : pageSize;
        this.pageIndex = pageStart < 1 ? 0 : (pageStart - 1) * this.pageSize;
    }

    /**
     * @param condition
     * @return
     *
     * @mbg.generated
     */
    public TweetInfoParam appendDistinct(OrderCondition condition) {
        if (null != distinctSql){
            distinctSql = distinctSql + ", " + condition.getColumnName();
        } else {
            distinctSql = condition.getColumnName();
        }
        return this;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * @return
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *
     * @mbg.generated
     */
    protected abstract static class AbstractGeneratedCriteria {
        protected List<Criterion> criteria;

        protected AbstractGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTweetIdIsNull() {
            addCriterion("tweet_id is null");
            return (Criteria) this;
        }

        public Criteria andTweetIdIsNotNull() {
            addCriterion("tweet_id is not null");
            return (Criteria) this;
        }

        public Criteria andTweetIdEqualTo(String value) {
            addCriterion("tweet_id =", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdNotEqualTo(String value) {
            addCriterion("tweet_id <>", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdGreaterThan(String value) {
            addCriterion("tweet_id >", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdGreaterThanOrEqualTo(String value) {
            addCriterion("tweet_id >=", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdLessThan(String value) {
            addCriterion("tweet_id <", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdLessThanOrEqualTo(String value) {
            addCriterion("tweet_id <=", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdLike(String value) {
            addCriterion("tweet_id like", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdNotLike(String value) {
            addCriterion("tweet_id not like", value, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdIn(List<String> values) {
            addCriterion("tweet_id in", values, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdNotIn(List<String> values) {
            addCriterion("tweet_id not in", values, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdBetween(String value1, String value2) {
            addCriterion("tweet_id between", value1, value2, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetIdNotBetween(String value1, String value2) {
            addCriterion("tweet_id not between", value1, value2, "tweetId");
            return (Criteria) this;
        }

        public Criteria andTweetNameIsNull() {
            addCriterion("tweet_name is null");
            return (Criteria) this;
        }

        public Criteria andTweetNameIsNotNull() {
            addCriterion("tweet_name is not null");
            return (Criteria) this;
        }

        public Criteria andTweetNameEqualTo(String value) {
            addCriterion("tweet_name =", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameNotEqualTo(String value) {
            addCriterion("tweet_name <>", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameGreaterThan(String value) {
            addCriterion("tweet_name >", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameGreaterThanOrEqualTo(String value) {
            addCriterion("tweet_name >=", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameLessThan(String value) {
            addCriterion("tweet_name <", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameLessThanOrEqualTo(String value) {
            addCriterion("tweet_name <=", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameLike(String value) {
            addCriterion("tweet_name like", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameNotLike(String value) {
            addCriterion("tweet_name not like", value, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameIn(List<String> values) {
            addCriterion("tweet_name in", values, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameNotIn(List<String> values) {
            addCriterion("tweet_name not in", values, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameBetween(String value1, String value2) {
            addCriterion("tweet_name between", value1, value2, "tweetName");
            return (Criteria) this;
        }

        public Criteria andTweetNameNotBetween(String value1, String value2) {
            addCriterion("tweet_name not between", value1, value2, "tweetName");
            return (Criteria) this;
        }

        public Criteria andBackUpIsNull() {
            addCriterion("back_up is null");
            return (Criteria) this;
        }

        public Criteria andBackUpIsNotNull() {
            addCriterion("back_up is not null");
            return (Criteria) this;
        }

        public Criteria andBackUpEqualTo(String value) {
            addCriterion("back_up =", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpNotEqualTo(String value) {
            addCriterion("back_up <>", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpGreaterThan(String value) {
            addCriterion("back_up >", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpGreaterThanOrEqualTo(String value) {
            addCriterion("back_up >=", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpLessThan(String value) {
            addCriterion("back_up <", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpLessThanOrEqualTo(String value) {
            addCriterion("back_up <=", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpLike(String value) {
            addCriterion("back_up like", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpNotLike(String value) {
            addCriterion("back_up not like", value, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpIn(List<String> values) {
            addCriterion("back_up in", values, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpNotIn(List<String> values) {
            addCriterion("back_up not in", values, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpBetween(String value1, String value2) {
            addCriterion("back_up between", value1, value2, "backUp");
            return (Criteria) this;
        }

        public Criteria andBackUpNotBetween(String value1, String value2) {
            addCriterion("back_up not between", value1, value2, "backUp");
            return (Criteria) this;
        }
    }

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends AbstractGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum OrderCondition {
        /**
         *
         */
        TWEETID("tweet_id"),
        /**
         *推主名, @后的那堆东西
         */
        TWEETNAME("tweet_name"),
        /**
         *备注名, 用于辨识出时哪个推主
         */
        BACKUP("back_up");

        private String columnName;

        OrderCondition(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        public static OrderCondition getEnumByName(String name) {
            OrderCondition[] orderConditions = OrderCondition.values();
            for (OrderCondition orderCondition : orderConditions) {
                if (orderCondition.name().equalsIgnoreCase(name)) {
                    return orderCondition;
                }
            }
            throw new RuntimeException("OrderCondition of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return columnName;
        }
    }

    /**
     *
     * @mbg.generated
     */
    public enum SortType {
        /**
         * 升序
         */
        ASC("asc"),
        /**
         * 降序
         */
        DESC("desc");

        private String value;

        SortType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public static SortType getEnumByName(String name) {
            SortType[] sortTypes = SortType.values();
            for (SortType sortType : sortTypes) {
                if (sortType.name().equalsIgnoreCase(name)) {
                    return sortType;
                }
            }
            throw new RuntimeException("SortType of " + name + " enum not exist");
        }

        @Override
        public String toString() {
            return value;
        }
    }
}