package com.ggemo.tweet.pojo.dao;

import com.ggemo.tweet.pojo.dos.BiliAccountDO;
import com.ggemo.tweet.pojo.dos.BiliAccountParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author 清纯的小黄瓜
 */
@Mapper
public interface BiliAccountDAO {
    /**
     * @param biliAccountParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(BiliAccountParam biliAccountParam);

    /**
     * @param biliAccountParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(BiliAccountParam biliAccountParam);

    /**
     * @param biliId
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long biliId);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(BiliAccountDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(BiliAccountDO record);

    /**
     * @param biliAccountParam
     * @return
     *
     * @mbg.generated
     */
    List<BiliAccountDO> selectByParamWithBLOBs(BiliAccountParam biliAccountParam);

    /**
     * @param biliAccountParam
     * @return
     *
     * @mbg.generated
     */
    List<BiliAccountDO> selectByParam(BiliAccountParam biliAccountParam);

    /**
     * @param biliId
     * @return
     *
     * @mbg.generated
     */
    BiliAccountDO selectByPrimaryKey(Long biliId);

    /**
     * @param record
     * @param biliAccountParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") BiliAccountDO record, @Param("biliAccountParam") BiliAccountParam biliAccountParam);

    /**
     * @param record
     * @param biliAccountParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamWithBLOBs(@Param("record") BiliAccountDO record, @Param("biliAccountParam") BiliAccountParam biliAccountParam);

    /**
     * @param record
     * @param biliAccountParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") BiliAccountDO record, @Param("biliAccountParam") BiliAccountParam biliAccountParam);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BiliAccountDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BiliAccountDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BiliAccountDO record);

    /**
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<BiliAccountDO> records);
}