package com.ggemo.tweet.pojo.dao;

import com.ggemo.tweet.pojo.dos.Tweet2qqDO;
import com.ggemo.tweet.pojo.dos.Tweet2qqParam;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author 清纯的小黄瓜
 */
@Mapper
public interface Tweet2qqDAO {
    /**
     * @param tweet2qqParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(Tweet2qqParam tweet2qqParam);

    /**
     * @param tweet2qqParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(Tweet2qqParam tweet2qqParam);

    /**
     * @param tweetId
     * @param qqGroupId
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("tweetId") String tweetId, @Param("qqGroupId") Integer qqGroupId);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(Tweet2qqDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(Tweet2qqDO record);

    /**
     * @param tweet2qqParam
     * @return
     *
     * @mbg.generated
     */
    List<Tweet2qqDO> selectByParam(Tweet2qqParam tweet2qqParam);

    /**
     * @param tweetId
     * @param qqGroupId
     * @return
     *
     * @mbg.generated
     */
    Tweet2qqDO selectByPrimaryKey(@Param("tweetId") String tweetId, @Param("qqGroupId") Integer qqGroupId);

    /**
     * @param record
     * @param tweet2qqParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") Tweet2qqDO record, @Param("tweet2qqParam") Tweet2qqParam tweet2qqParam);

    /**
     * @param record
     * @param tweet2qqParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") Tweet2qqDO record, @Param("tweet2qqParam") Tweet2qqParam tweet2qqParam);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tweet2qqDO record);

    /**
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tweet2qqDO record);

    /**
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<Tweet2qqDO> records);
}